# Generated by Django 2.1.1 on 2018-09-15 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('عنوان_الاعلان', models.CharField(max_length=250)),
                ('المنطقة', models.CharField(max_length=250)),
                ('عدد_الغرف', models.IntegerField(blank=True, null=True)),
                ('المساحه', models.IntegerField(blank=True, null=True)),
                ('الموقع', models.CharField(max_length=250)),
                ('الوصف', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('حالة_العقار', models.CharField(max_length=250)),
                ('تاريخ_الاعلان', models.DateTimeField(auto_now=True)),
                ('تاريخ_تعديل_الاعلان', models.DateTimeField(auto_now_add=True)),
                ('خصوصي', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='subCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SubCategory'),
        ),
    ]
